apiVersion: apps/v1
kind: Deployment

metadata:
  name: catalog-api-deployment
  labels:
    app: catalog-api

spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: catalog-service
        image: carlosengel013/catalog-service:latest
        volumeMounts:
        - name: catalog-service-storage
          mountPath: /var/lib/catalog-service
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:  
      - name: catalog-service-storage
        emptyDir: {}