
apiVersion: apps/v1
kind: Deployment

metadata:
  name: catalog-api-deployment
  labels:
    app: catalog-api

spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: catalog-service
        image: carlosengel013/catalog-service:latest
        volumeMounts:
        - name: catalog-service-storage
          mountPath: /var/lib/catalog-service

        envFrom:
          - configMapRef:
              name: catalog-service-config
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
      volumes:  
      - name: catalog-service-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service

metadata:
  name: catalog-service
  labels:
    app: catalog-service

spec:
  selector:
    app: catalog-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
